### ISSUE TITLE
error: repository "community" was not found.

### ISSUE THREAD

**Issue by KwisatzJim** [gavinlyonsrepo/cylon#10]
from the main menu, chose 8) System Information, then 'y' for page 2 and again for page 3 and there are 2 lines that say "error: repository "community" was not found."

This appears to be when calling this:
`msgFunc norm "Community: $(paclist community | wc -l)"`

and

`msgFunc norm "Community: $(pacman -Qi $(paclist community | awk '{print $1}' ) | awk '/Installed Size/ {if ($5=="MiB") {sum+=$4} else if ($5=="KiB") {sum+=($4/1024)}} END {print sum " MiB"}')"`

The community repository was merged with extra May 2023

**Comment by gavinlyonsrepo** [comment]
Hi  

Version 6.3-4 released today correcting this.

Thanks.
