### ISSUE TITLE
openbsd-netcat

### ISSUE THREAD

**Issue by du5tball** [gavinlyonsrepo/cylon#3]
Please add support for openbsd-netcat, not every system has the gnu-version installed, and virt-manager (hypervisor-interface) for example has a hard dependency on the openbsd version, making it unremovable.

**Comment by gavinlyonsrepo** [comment]
Hi

Thanks for feedback. I will look into this and provide a solution at next upgrade point.
Regards

**Comment by gavinlyonsrepo** [comment]
Hi

Support for openbsd-netcat added to version 3.1-2 now released.

regards
