### ISSUE TITLE
Don't display unavailable menu items

### ISSUE THREAD

**Issue by du5tball** [gavinlyonsrepo/cylon#4]
Please either remove menu items which don't have the needed dependencies installed, or display them in another color.

**Comment by gavinlyonsrepo** [comment]
Hi

I don't agree  with removing them I think its better user to see everything in main menu.
There is error handling in all the functions to deal with missing dependencies 
in addition the installed dependencies are scanned for cylon information page and are in readme.md file. Also some menu options require multiple dependencies for different sub-sections of main options.
for example "System backup" uses rsync for one option and gdrive for another option
both options totally separate functions. So its complicated.

I will review this again when next upgrade happens and see if a coloured text solution can be found.
Leave open for now.

Regards

**Comment by gavinlyonsrepo** [comment]
In version 3.3-4 menu items with uninstalled  needed dependencies will be marked with "n/a"
