### ISSUE TITLE
Rename file output

### ISSUE THREAD

**Issue by du5tball** [gavinlyonsrepo/cylon#5]
Currently, the format seems to be [hour][minute][DOW][month][day]-[command].

I suggest a more readable format of [year]-[month]-[day]-[hour]-[minute]-[command].

**Comment by gavinlyonsrepo** [comment]
Hi 
Thanks fro feedback.

File output changed to  HHMM-DDMMMYY-command in version 3.1-2 now released.
for example
**original** 
2134MonDec20-BACKUP
**version 3.1-2**
2134-20Dec16-BACKUP

Regards
