### ISSUE TITLE
error: group 'base-devel' was not found

### ISSUE THREAD

**Issue by KwisatzJim** [gavinlyonsrepo/cylon#9]
from the main menu, chose 8) System Information, then 'y' for page 2 and 6th line down will say "error: group 'base-devel' was not found"

This appears to be when calling this:
```
msgFunc norm "All explicitely installed pkgs not in base-devel grps: \
$(comm -23 <(pacman -Qeq | sort) <(pacman -Qgq base-devel | sort) | wc -l ) "
```

looks like since this was written base-devel has become a meta package, and no longer a group.  Perhaps the command should be changed to pacman -Qnq base-devel instead?

**Comment by gavinlyonsrepo** [comment]
Hi  

Version 6.3-4 released today correcting this.

Thanks.
